export const municipiosAntioquia = [
  {
    nombre: "ABEJORRAL",
    barrios: [
      " Carrizales",
      " La Peña",
      " La Victoria",
      " Piedra Candela",
      " Purima",
      "Altamira",
      "Alto Bonito",
      "Alto de Letras",
      "Aures Arriba",
      "Aures El Silencio",
      "Cabuyal",
      "Cañaveral",
      "Chagualal",
      "Combia",
      "Corinto",
      "El Buey",
      "El Buey Colmenas",
      "El Carmelo",
      "El Caunzal",
      "El Chagualo",
      "El Erizo",
      "El Granadillo",
      "El Guadual",
      "El Guaico",
      "El Reposo",
      "El Vesubio",
      "El Volcan",
      "Guayabal",
      "Guyaquil",
      "La Albania",
      "La Betulia",
      "La Cascada",
      "La Circita",
      "La Cordillera",
      "La Esperanza",
      "La Floresta",
      "La Florida",
      "La Labo",
      "La Llanada",
      "La Mata de Guadua",
      "La Perdida",
      "La Polka",
      "La Primavera",
      "La Saltadera",
      "La Samaria",
      "Llano Grande",
      "Loma Parte Baja",
      "Loma parte Alta",
      "Los Rastrojos",
      "Morrogordo",
      "Morrón",
      "Naranjal",
      "Pantano Negro",
      "Portugal",
      "Quebradanegra",
      "Quebradona Abajo",
      "Quebradona Arriba",
      "San Bartolome y San Bosco",
      "San Bernardo",
      "San Jose",
      "San José",
      "San Luis",
      "San Pedro",
      "San Vicente",
      "Santa Ana",
      "Santa Catalina",
      "Sotayac",
      "Yarumal",
    ],
  },
  {
    nombre: "AMAGA",
    barrios: [
      "Camilocé",
      "La Clarita",
      "La Ferreira",
      "La Gualí",
      "Maní de las Casas",
      "Minas",
      "No registra barrio-vereda",
      "Piedecuesta",
    ],
  },
  {
    nombre: "AMALFI",
    barrios: [
      "El Lagarto",
      "El Mata",
      "La Cancana",
      "La Clara",
      "La Cruz",
      "La Pasionaria",
      "La Virgen",
      "La Víbora",
      "No registra barrio-vereda",
      "San Agustín",
      "Tequendama",
      "Trinitá",
    ],
  },
  {
    nombre: "ARGELIA",
    barrios: [
      "Alto Bonito",
      "Alto de Samana",
      "Arenillal",
      "Buena Vista",
      "Buenos Aires",
      "Chamberry",
      "Claras",
      "El Bosque",
      "El Bujio",
      "El Cabuyo",
      "El Café",
      "El Diamante",
      "El Diviso",
      "El Dragal",
      "El Fresnito",
      "El Guadual",
      "El Mango",
      "El Naranjal",
      "El Oro",
      "El Perú",
      "El Pital",
      "El Plan",
      "El Plateado",
      "El Recreo",
      "El Retiro",
      "El Rosario",
      "El Silencio",
      "El Sinaí",
      "El Zancudo",
      "Guadualito",
      "Guaimaral",
      "Guayabal",
      "La Arabia",
      "La Belleza",
      "La Emboscada",
      "La Estrella",
      "La Julia",
      "La Manuela",
      "La Margarita",
      "La Mina",
      "La Osa",
      "La Plata",
      "La Primavera",
      "La Quiebra",
      "La Reina",
      "Mesones",
      "Puerto Rico",
      "Rancho Largo",
      "San Agustín",
      "San Juan",
      "San Juan de la Florida",
      "San Juan de la Guadua",
      "San Luis",
      "San Pablo",
      "Santa Clara",
      "Santa Teresa La Arboleda",
      "Tabanales",
      "Villeta Florida",
      "Yarumal",
    ],
  },
  {
    nombre: "BARBOSA",
    barrios: [
      "Aguas Claras Abajo",
      "Aguas Claras Arriba",
      "Altamira",
      "Buenos Aires",
      "Buga",
      "Cestillal",
      "Chapa Baja",
      "Chorro Hondo",
      "Corrientes",
      "Dos Quebradas",
      "El Cortado",
      "El Guayabo",
      "El Hatillo",
      "El Hoyo",
      "El Paraíso",
      "El Tablazo Hatillo",
      "El Tablazo Popalito",
      "El Tigre",
      "El Viento",
      "Filo Verde",
      "Graciano",
      "Guayabal",
      "Isaza",
      "La Aguada",
      "La Calda",
      "La Cejita",
      "La Chapa Alta",
      "La Chorrera",
      "La Cuesta",
      "La Ese",
      "La Gómez",
      "La Herradura",
      "La Lomita",
      "La Montañita",
      "La Playa",
      "La Quiebra",
      "La Tolda",
      "Las Lajas",
      "Las Peñas",
      "Las Victorias",
      "Matasanos",
      "Mocorongo",
      "Monteloro",
      "No registra barrio-vereda",
      "Pachohondo",
      "Pantanillo",
      "Platanito Parte Alta",
      "Platanito Parte Baja",
      "Popalito",
      "Potrerito",
      "Quintero",
      "San Eugenio",
      "Tablazo Popalito",
      "Tamborcito",
      "Vallecitos",
      "Ventanas",
      "Volantín",
      "Yarumito",
    ],
  },
  {
    nombre: "BELLO",
    barrios: [
      "Altavista",
      "Altavista",
      "Altos de Niquía",
      "Amazonia",
      "Anda lucia",
      "Araucarias",
      "Barrio central",
      "Barrio nuevo",
      "Barrio obrero",
      "Bellavista",
      "Bucaros",
      "Cabañas",
      "Cabañita",
      "Calle vieja",
      "Carmelo",
      "Central espiritu santo",
      "Central espiritu santo",
      "Centro",
      "Ciudadela del Norte",
      "Ciudadela del Norte",
      "Congolo",
      "Corregimiento-San felix",
      "El Cafetal",
      "El Cafetal",
      "El Carmelo",
      "El Carmelo",
      "El cafetal",
      "El cafetal",
      "El cairo",
      "El cairo",
      "El mirador",
      "El mirador",
      "El porvenir",
      "El rosal",
      "El rosalpi",
      "El rosario",
      "Fabricato",
      "Fontidueño",
      "Girasoles",
      "Girasoles",
      "Gran avenida",
      "Gran avenida",
      "Granavenida",
      "Granjas",
      "Granjas",
      "Guasimalito",
      "Hermosa provincia",
      "Jardines de la fe",
      "José Antonio Galán",
      "José Antonio Galán",
      "La Cumbre",
      "La Esmeralda",
      "La Esmeralda",
      "La Madera",
      "La Maruchenga",
      "La Pradera",
      "La Primavera",
      "La Primavera",
      "La acuarela",
      "La aldea",
      "La camila",
      "La estación",
      "La estación",
      "La florida",
      "La gabriela",
      "La meseta",
      "La meseta",
      "Las vegas",
      "Los Alpes",
      "Los Alpes",
      "Los Sauces",
      "Los Sauces",
      "López de Mesa",
      "López de Mesa",
      "Madera",
      "Manchester",
      "Maruchenga",
      "Maruchenga",
      "Mirador quinta",
      "Molinares",
      "NO CONCRETADO",
      "Navarra",
      "Nazareth",
      "Nazareth",
      "Niquia camacol",
      "Niquia los angeles",
      "Niquia parte baja",
      "Niquía",
      "No registra barrio",
      "Nueva Jerusalén",
      "Nueva Jerusalén",
      "Nuevo Bello",
      "Pachelly",
      "Panamericano",
      "Panorama",
      "Panorama",
      "París",
      "Perez",
      "Picacho",
      "Picacho",
      "Playa rica",
      "Prado",
      "Puerto Bello ",
      "Puerto Bello ",
      "Riachuelos",
      "Rincon santos",
      "Rincon santos",
      "Salento",
      "Salento",
      "Salvador Allende",
      "Salvador Allende",
      "San José Obrero",
      "San José Obrero",
      "San Martin",
      "San Simon",
      "San Simon",
      "San gabriel",
      "Santa Ana",
      "Santa rita",
      "Sarramonte",
      "Serramonte-Bello",
      "Suárez",
      "Terranova",
      "Toledo",
      "Trapiche",
      "Valerias",
      "Vereda Hato viejo",
      "Villa Maria",
      "Villa Maria",
      "Villa del sol",
      "Villas de comfenalco",
      "Villas de occidente",
      "Villas de occidente",
      "Zamora",
      "prueba",
    ],
  },
  {
    nombre: "BURITICA",
    barrios: [
      "Angelina",
      "Buenavista",
      "Cabecera Municipal",
      "Carauquia",
      "El León",
      "El Llano Grande",
      "El Puente",
      "Higabra",
      "La Cordillera",
      "La Fragua",
      "Las Brisas",
      "Las Cuatro",
      "Los Asientos",
      "Mogotes",
      "Murruapal",
      "No registra barrio-vereda",
      "Palenque",
      "Paraje Alto del Obispo",
      "Tabacal",
    ],
  },
  {
    nombre: "CALDAS",
    barrios: [
      "Aburra sur",
      "Andalucía",
      "Barrio Nuevo",
      "Barrios Unidos",
      "Bellavista",
      "Cardalito",
      "Centenario",
      "Cristo Rey",
      "El Cano",
      "El Porvenir",
      "El Raizal",
      "El Socorro",
      "Felipe Echavarría No. 1",
      "Felipe Echavarría No. 2",
      "Fundadores",
      "Juan XXIII",
      "Kaiser",
      "La Acuarela y/o La Rivera",
      "La Aguacatala",
      "La Buena Esperanza",
      "La Chuscala",
      "La Chuscala",
      "La Clara",
      "La Corrala",
      "La Corralita",
      "La Docena",
      "La Goretti",
      "La Inmaculada",
      "La Maní de Cardal",
      "La Miel",
      "La Planta",
      "La Playita",
      "La Pradera",
      "La Quiebra",
      "La Raya",
      "La Salada (P.A.)",
      "La Salada (P.B.)",
      "La Tolva",
      "La Valeria",
      "Las Margaritas",
      "Los Cerezos",
      "Mandalay",
      "Minas",
      "Minuto",
      "Minuto de Dios",
      "No registra barrio-vereda",
      "Olaya Herrera",
      "Parque de caldas",
      "Potrerillo",
      "Primavera",
      "Salinas",
      "San Félix",
      "Sinífana",
      "Villa Capri",
      "Villa Capri",
      "Villa del Sol",
      "Zona Centro",
    ],
  },
  {
    nombre: "COCORNÁ",
    barrios: [
      "Agua Bonita",
      "Agualinda",
      "Alto Bonito",
      "Balcones",
      "Buenos Aires",
      "Campo Alegre",
      "Caracolí",
      "Cebaderos",
      "Cruces",
      "El Alto de la Virgen",
      "El Chocó",
      "El Ciprés",
      "El Coco",
      "El Cocuyo",
      "El Entablado",
      "El Estío, El Retiro",
      "El Higuerón",
      "El Jordán",
      "El Molino",
      "El Molino",
      "El Palmar",
      "El Porvenir",
      "El Roblal",
      "El Sinaí",
      "El Suspiro",
      "El Tesoro",
      "El Viaho",
      "Guayabal",
      "La Aurora",
      "La Chorrera",
      "La Cima",
      "La Cuchilla del Rejo",
      "La Granja",
      "La Inmaculada",
      "La Milagrosa",
      "La Paila",
      "La Peña",
      "La Piñuela",
      "La Piñuela",
      "La Placeta",
      "La Quiebra",
      "La Secreta",
      "La Solita",
      "La Tolda",
      "La Trinidad",
      "La Vega",
      "La Veta",
      "Las Mercedes",
      "Las Playas",
      "Los Limones",
      "Los Mangos",
      "Los Potreros",
      "Majagual",
      "Mazotes",
      "Media Cuesta",
      "Montañita",
      "Morritos",
      "Pailania",
      "Pailania",
      "Salado",
      "San Antonio",
      "San Juan",
      "San Lorenzo",
      "San Martín",
      "San Miguel",
      "San Vicente",
      "Santa Bárbara",
      "Santa Cruz",
      "Santa Rita",
      "Santo Domingo",
      "Tres centros poblados",
      "Vereda La Florida",
      "Viadal",
      "Villa Hermosa",
      "vereda La Arboleda",
    ],
  },
  {
    nombre: "COPACABANA",
    barrios: [
      "Alvarado",
      "Ancón",
      "Asunción",
      "Autopista (Industrial)",
      "Cabuyal",
      "Centro",
      "Cristo Rey",
      "El Convento",
      "El Mojón",
      "El Noral",
      "El Salado",
      "Fatima",
      "Fontidueño",
      "Francisco Meneses",
      "Granizal",
      "Horizontes",
      "La Lomita (Luna Lunera)",
      "La Misericordia",
      "La Veta",
      "La azulita",
      "La maria",
      "Las vegas",
      "Machado",
      "Miraflores",
      "Montañita",
      "No registra barrio-vereda",
      "Obrero",
      "Pedregal",
      "Peñolcito",
      "Quebrada Arriba",
      "Recreo",
      "Remanso",
      "Sabaneta",
      "San Francisco",
      "San Juan ",
      "Simon bolivar",
      "Tobón Quintero",
      "Villa Nueva",
      "Yarumito",
      "Zarzal Curazao",
      "Zarzal La Luz",
    ],
  },
  {
    nombre: "EL CARMEN DE VIBORAL",
    barrios: [
      "Alto Grande",
      "Buenos Aires",
      "Campo Alegre",
      "Centro",
      "Cristo Rey",
      "El Cerro",
      "El Edén",
      "El Progreso",
      "El Retiro",
      "El Salado",
      "Fundadores",
      "Guamito",
      "La Alhambra",
      "La Aurora",
      "La Bomba",
      "La Boquía",
      "La Ceja",
      "La Chapa",
      "La Esmeralda",
      "La Esperanza",
      "La Loma",
      "La Madera",
      "La María",
      "La Milagrosa",
      "La Primavera",
      "La Sonadora",
      "No registra barrio-vereda",
      "Ospina",
      "Quirama",
      "Samaria",
      "San José",
      "Santa Ana",
      "Tahamíes",
      "Villa María",
    ],
  },
  {
    nombre: "EL RETIRO",
    barrios: [
      "Bicentenario",
      "Brisas del Edén",
      "Chapineros",
      "Corvisol",
      "El Corralito",
      "El Pino",
      "El Plan",
      "El Rosario",
      "Guanteros",
      "La Acuarela",
      "La Aldea",
      "La Capilla",
      "La Glorieta",
      "La Libertad",
      "La Macarena",
      "Martin Pescador",
      "No registra barrio-vereda",
      "Pinares",
      "Puente Colorado",
      "Retiro Campestre",
      "Retiro del Viento",
      "Riberas",
      "Santa Ana",
      "Sector Centro",
    ],
  },
  {
    nombre: "ENTRERRIOS ANTIOQUIA",
    barrios: [
      "El Filo",
      "El Peñol",
      "El Progreso",
      "El Zancudo",
      "Las Brisas",
      "No registra barrio-vereda",
      "Porvenir",
      "Pío XII",
      "Río Chico",
      "Río Grande",
      "Tesorero",
      "Toruro",
      "Yerbabuenal",
    ],
  },
  {
    nombre: "ENVIGADO",
    barrios: [
      "Alcalá",
      "Alto de las flores",
      "Alto del escobero",
      "Altos de misael",
      "Barrio Abajo",
      "Barrio Arriba",
      "Barrio obrero",
      "Barrios Mesa",
      "Barrios Mesa",
      "Beneditinos",
      "Bosques de esmeraldal",
      "Bucarest",
      "Bucarest",
      "Camino verde",
      "El Carmen",
      "El Chocho",
      "El Dorado",
      "El Esmeraldal",
      "El Portal",
      "El Portal de Envigado",
      "El Portal de San Pedro",
      "El Portal de la Villa",
      "El Portal del Tesoro",
      "El Salado",
      "El Trianón",
      "El Triángulo",
      "El chingui",
      "El penasco",
      "El vergel",
      "El vergel",
      "GUAIMARO",
      "Gualandayes",
      "Gualandayes",
      "Guanteros-zona 9",
      "Isla fuerte",
      "Jardines",
      "La Abadía",
      "La Candelaria",
      "La Inmaculada",
      "La Magnolia",
      "La Mina",
      "La Paz",
      "La Pradera",
      "La Primavera",
      "La Sebastiana",
      "La frontera",
      "La intermedia",
      "La orquidea",
      "La purisima",
      "Las antillas",
      "Las casitas",
      "Las cometas",
      "Las cumbres",
      "Las flores",
      "Las mercedes",
      "Las vegas",
      "Loma de las brujas",
      "Loma de los benedictinos",
      "Loma del atravesado",
      "Loma del barro",
      "Loma del chocho",
      "Loma del esmeraldal",
      "Loma del indio",
      "Loma del indio",
      "Loma escobero",
      "Los almendros",
      "Los almendros",
      "Los cristales",
      "Los naranjos",
      "Los naranjos",
      "Manga azul",
      "Mesa",
      "Mesitas",
      "Milan",
      "NO CONCRETADO",
      "No registra barrio",
      "Oasis",
      "Obrero",
      "Obrero",
      "Otra parte",
      "Parque de envigado",
      "Pio XII",
      "Pio XII",
      "Pontevedra",
      "San Lucas",
      "San Marcos",
      "San Marcos",
      "San jorge",
      "San jorge tres esquinas",
      "San jose",
      "San mateo",
      "San rafael",
      "Señorial",
      "Sol de plata",
      "Trianon",
      "Uribe Ángel",
      "Uribe Ángel",
      "Vereda-las palmas",
      "Villa grande",
      "Villanovoa",
      "Villas del esmeraldal",
      "Zona 7",
      "Zúñiga",
    ],
  },
  {
    nombre: "El Peñol",
    barrios: [
      "Balsas",
      "Bonilla",
      "Chiquinquirá",
      "Comuneros",
      "Concordia",
      "Conquistadores",
      "Despensas",
      "El Carmelo",
      "El Carmelo",
      "El Chilco",
      "El Marial",
      "El Morro",
      "El Porvenir",
      "El Salto",
      "El Uvital",
      "Florito",
      "Florito",
      "Guamito",
      "Horizontes",
      "La Asunción",
      "La Chapa",
      "La Cristalina",
      "La Culebra",
      "La Hélida",
      "La Inmaculada",
      "La Magdalena",
      "La Meseta",
      "La Milagrosa",
      "Palestina",
      "Palmira",
      "San José",
      "San Judas",
      "Santa Ana",
      "Santa Inés",
    ],
  },
  {
    nombre: "GIRARDOTA",
    barrios: [
      "Aurelio Mejía",
      "Centro",
      "El Barro",
      "El Cano",
      "El Llano ",
      "El Palmar",
      "El Paraiso",
      "El Salado",
      "El Socorro",
      "El Totumo",
      "Encenillo",
      "Ferreria",
      "Filo Verde",
      "Florida",
      "Girardota la Nueva",
      "Guadales",
      "Guarne",
      "Guayacanes",
      "Hato Grande",
      "Jamundi",
      "Juan Cojo",
      "Juan XXII",
      "La Calera",
      "La Ceiba",
      "La Enea",
      "La Holanda",
      "La Mata",
      "La Matica",
      "La Mejía",
      "La Meseta",
      "La Palma",
      "Las Cuchillas",
      "Loma de los Ochoa",
      "Manga Arriba",
      "Mercedes Abrego",
      "Montecarlo",
      "Naranjal",
      "No registra barrio-vereda",
      "Nuevo Horizonte",
      "Portachuelo",
      "Potrerito",
      "San Andrés",
      "San Diego ",
      "San Esteban",
      "San José",
      "Santa Ana",
      "Yarumo",
    ],
  },
  {
    nombre: "GUARNE",
    barrios: [
      "Alcores",
      "Alto de la Virgen",
      "Barro Blanco",
      "Batea Seca",
      "Bellavista",
      "Berracal",
      "Canoas",
      "Chaparral",
      "Charanga",
      "El Carmelo",
      "El Centro",
      "El Colorado",
      "El Molino",
      "El Palmar",
      "El Porvenir",
      "El Salado",
      "El Sango",
      "Garrido",
      "Guamito",
      "Guapante",
      "Hojas Anchas",
      "Juan XXIII",
      "La Alborada",
      "La Asunción",
      "La Brizuela",
      "La Cabaña",
      "La Clara",
      "La Enea",
      "La Honda",
      "La Hondita",
      "La Inmaculada",
      "La Mejía",
      "La Milagrosa",
      "La Mosca",
      "La Mosquita",
      "La Pastorcita",
      "La guitarra",
      "Montañez",
      "No registra barrio-vereda",
      "Piedras Blancas",
      "Romeral",
      "San Antonio",
      "San Ignacio",
      "San Isidro",
      "San José",
      "San Vicente",
      "Toldas",
      "Vereda Guamito",
      "Vereda tolda",
      "Yolombal",
    ],
  },
  {
    nombre: "GUATAPE",
    barrios: [
      "El Peñol",
      "El Rosario",
      "La Loma",
      "La Peña",
      "La Piedra",
      "La Sonadora",
      "Los Naranjos",
      "No registra barrio-vereda",
      "Quebrada Arriba",
      "Roble",
      "Santa Rita",
    ],
  },
  {
    nombre: "ITAGUI",
    barrios: [
      "19 de Abril",
      "19 de Abril",
      "Altavista",
      "Araucaria",
      "Artex",
      "Asturias",
      "Balcones de sevilla",
      "Barrio Pilsen ",
      "Barrio la union",
      "Calatrava",
      "Camparola",
      "Campo Amor",
      "Central mayorista",
      "Centro",
      "Colinas del Sur",
      "Ditaires",
      "El Ajizal",
      "El Corazón",
      "El Crucero",
      "El Diamante",
      "El Edén",
      "El Guayabo",
      "El Palmar",
      "El Palmar",
      "El Pesebre",
      "El Porvenir",
      "El Progreso",
      "El Rosal",
      "El Rosario",
      "El Salado",
      "El Tablazo",
      "El Trapiche",
      "El Trébol",
      "El carmelo",
      "Fatima",
      "Ferrara",
      "Jardines Montesacro",
      "La Aldea",
      "La Asomadera",
      "La Estrella",
      "La Gloria",
      "La Guayacana",
      "La Independencia",
      "La Palma",
      "La Playita",
      "La Pradera",
      "La Víbora",
      "La esmeralda",
      "La finquita",
      "La maria",
      "Las Américas",
      "Las Brisas",
      "Las Margaritas",
      "Las acacias",
      "Las mercedes",
      "Loma de los Zuleta",
      "Los Olivares",
      "Los gomez",
      "Los naranjos",
      "Malta",
      "Mayorista",
      "Monte Verde",
      "NO CONCRETADO",
      "No registra barrio",
      "Parque obrero-Obrero",
      "Pedregal",
      "Pilsen",
      "Playa Rica",
      "Portal de ditaires",
      "Samaria",
      "Samaria N.º 1",
      "San Antonio",
      "San Fernando",
      "San Francisco",
      "San Isidro",
      "San Javier",
      "San Juan Bautista",
      "San Pio X",
      "San agustin",
      "San bernando-Mayorista",
      "San gabriel",
      "San jose",
      "San pablo",
      "San pio",
      "Santa Ana",
      "Santa Maria La Nueva",
      "Santa María",
      "Santa catalina",
      "Santa cruz",
      "Santa maria Nº1",
      "Santa maria Nº2",
      "Santa maria Nº3",
      "Satexco",
      "Satexco",
      "Simon bolivar",
      "Suramerica",
      "Triana",
      "VILLAVENTURA",
      "Vereda-ajizal",
      "Villa Lucía",
      "VillaLia",
      "VillaPaula",
      "Viviendas del sur",
      "Yarumito",
      "Zona Industrial N.º 1",
      "Zona Industrial N.º 2",
    ],
  },
  {
    nombre: "LA CEJA",
    barrios: [
      "Aguas Claras",
      "Cuatro Esquinas",
      "El Capiro",
      "El Centro Poblado",
      "El Chuscal",
      "El Tambo",
      "Fray Eugenio",
      "Fátima",
      "Guamito",
      "Higuerón",
      "La Amapola",
      "La Loma",
      "La Miel",
      "La Milagrosa",
      "La Palmera",
      "La Playa",
      "Llanadas",
      "No registra barrio-vereda",
      "Pantanillo",
      "Piedras",
      "Piedras y Colmenares",
      "Pontezuela",
      "San Cayetano",
      "San Gerardo",
      "San José",
      "San Rafael",
      "Villas de santa maria",
    ],
  },
  {
    nombre: "LA ESTRELLA",
    barrios: [
      "Ancón San Martín",
      "Barrios unidos",
      "Bellavista",
      "Camilo Torres",
      "Caqueta",
      "Centro",
      "Chile",
      "El Dorado",
      "El Pedrero",
      "Escobar",
      "Ferreria",
      "Horizontes",
      "La Bermejala",
      "La Chinca",
      "La Ferreira",
      "La Ferreria",
      "La Ospina",
      "La Raya",
      "La Tablacita",
      "La Tablaza",
      "La inmaculada 1",
      "Las Brisas",
      "Monterrey",
      "NO CONCRETADO",
      "No registra barrio",
      "Peñas Blancas",
      "Primavera",
      "Quebrada Grande",
      "Quintas de la quinta",
      "San Agustín",
      "San Andrés",
      "San Cayetano",
      "San Isidro",
      "San José",
      "San José Tarapacá",
      "San Miguel",
      "San Vicente",
      "Toledo",
      "Vereda-El guayabo",
      "Villa Alicia",
      "Villa Mira",
      "Villada",
      "Zona Industrial",
    ],
  },
  {
    nombre: "LA PINTADA",
    barrios: ["PEÑALIZA"],
  },
  {
    nombre: "MARINILLA",
    barrios: [
      "Alcaravanes",
      "Aldana",
      "Alto de San Jose",
      "Alto de la Ramada",
      "Alto del Calvario",
      "Alto del Mercado",
      "Alto grande",
      "Belen",
      "Bellavista",
      "Bellavista Occidente",
      "Belén Norte",
      "Belén Sur",
      "Bodegas",
      "Bodeguitas",
      "Botero González",
      "Campo Abajo",
      "Campo Alegre",
      "Campo Arriba",
      "Carolina Gómez",
      "Central",
      "Chagualo",
      "Chagualo Sur",
      "Chocho Mayo",
      "Cimarronas",
      "Ciudadela Artesanal",
      "Colvillas",
      "Cristo Rey",
      "Cuchillas",
      "El Caramelo",
      "El Carmen",
      "El Convento",
      "El Hato",
      "El Manantial",
      "El Pinar",
      "El Recodo",
      "El Recreo",
      "El Rosario",
      "El Socorro",
      "El Triángulo",
      "Gaitán",
      "Gaviria",
      "Horizontes",
      "Industrial",
      "Juan XXIII",
      "La Amistad",
      "La Asunción",
      "La Dalia",
      "La Esperanza",
      "La Esperanza PB",
      "La Inmaculada",
      "La Milagrosa",
      "La Peña",
      "La Primavera",
      "Las Acacias",
      "Las Cabañas",
      "Las Margaritas",
      "Las Mercedes",
      "Los Alpes",
      "Los Rosales",
      "Maria Auxiliadora",
      "Montañita",
      "No registra barrio-vereda",
      "Pablo Sexto",
      "Porvenir",
      "Pozo",
      "Ramada",
      "Salto Abajo",
      "Salto Arriba",
      "San Jose",
      "San Juan Bosco",
      "San Juan de Dios",
      "Santa Ana",
      "Santa Cruz",
      "Simona Duque",
      "Tinajas",
      "Urbanización La Florida",
      "Urbanización Los Alpes",
      "Urbanización Los Cedros",
      "Urbanización Monteverde",
      "Yarumos",
    ],
  },
  {
    nombre: "MEDELLIN",
    barrios: [
      "Aguacatala",
      "Aldea Pablo VI",
      "Alejandro Echavarría",
      "Alejandría",
      "Alfonso López",
      "Alpujarra",
      "Alpujarra",
      "Altamira",
      "Altavista",
      "Altos del Poblado",
      "Andalucía",
      "Antonio Nariño",
      "Aranjuez",
      "Asomadera Nº 1",
      "Asomadera Nº 2",
      "Asomadera Nº 3",
      "Astorga",
      "Aures Nº 1",
      "Aures Nº 2",
      "Autopista-norte",
      "Av cundinamarca",
      "Barrio Caicedo",
      "Barrio Colombia",
      "Barrio Colón",
      "Barrio Cristóbal",
      "Barrio Facultad de Minas Universidad Nac",
      "Barrio antioquia",
      "Barrios de Jesús",
      "Batallón Girardot",
      "Belalcazar",
      "Belen",
      "Belen Altavista",
      "Belen Rincon",
      "Belen alameda",
      "Belen aliadas",
      "Belen alpes",
      "Belen altavista parte baja",
      "Belen fatima",
      "Belen granada",
      "Belen la gloria",
      "Belen la mota",
      "Belen la nubia",
      "Belen la palma",
      "Belen las margaritas",
      "Belen las mercedes",
      "Belen las playas",
      "Belen loma de los bernal",
      "Belen los alpes",
      "Belen malibu",
      "Belen miravalle",
      "Belen nogal",
      "Belen porvenir",
      "Belen rosales",
      "Belen san bernardo",
      "Belen violetas",
      "Belen-buena vista",
      "Belencito",
      "Bello Horizonte",
      "Belén",
      "Berlín",
      "Bermejal – Los Álamos",
      "Betania",
      "Blanquizal",
      "Bolivariana",
      "Bombona Nº 2",
      "Bombona medellin",
      "Bombona-el pinal",
      "Bomboná Nº 1",
      "Bosques de San Pablo",
      "Boston",
      "Boyaca-Las brisas",
      "Boyacá",
      "Brasilia",
      "Buenos Aires",
      "Caicedo",
      "Calasanz",
      "Calasanz Parte Alta",
      "Calle Nueva",
      "Campo Alegre",
      "Campo Amor",
      "Campo Valdes Nº 1",
      "Campo Valdes Nº 2",
      "Campo valdez",
      "Carabobo",
      "Caribe",
      "Carlos E. Restrepo",
      "Carpinelo",
      "Castilla",
      "Castropol",
      "Cataluña",
      "Caunces buenos aires",
      "Centro",
      "Cerro El Volador",
      "Cerro Nutibara",
      "Ciudad del rio",
      "Cola del zorro",
      "Colón",
      "Colón",
      "Comuna 13",
      "Conquistadores",
      "Corazón de Jesús",
      "Cordoba-medellin",
      "Cristo Rey",
      "Cuarta Brigada",
      "Cucaracho",
      "Córdoba",
      "Diego Echevarria",
      "Doce de Octubre Nº 1",
      "Doce de Octubre Nº 2",
      "Eduardo Santos",
      "El Castillo",
      "El Chagualo",
      "El Compromiso",
      "El Corazón",
      "El Danubio",
      "El Diamante",
      "El Diamante Nº 2",
      "El Nogal – Los Almendros",
      "El Pesebre",
      "El Pinal",
      "El Playón de Los Comuneros",
      "El Poblado",
      "El Pomar",
      "El Progreso",
      "El Raizal",
      "El Rincón",
      "El Rodeo",
      "El Salado",
      "El Salvador",
      "El Socorro",
      "El Tesoro",
      "El Triunfo",
      "El Velódromo",
      "El Vergel",
      "El Vergel",
      "El congolo",
      "El hueco-centro",
      "El verguel-San anotnio de prado",
      "Enciso",
      "Enciso el pinal",
      "Enciso golondrinas",
      "Enciso los mangos",
      "Estación Villa",
      "Estación Villa",
      "Estación Villa",
      "Estadio",
      "Ferrini",
      "Florencia",
      "Floresta",
      "Florida Nueva",
      "Francisco Antonio Zea",
      "Fuente Clara",
      "Fátima",
      "Gerona",
      "Girardot",
      "Granada",
      "Granizal",
      "Gratamira",
      "Guayabal",
      "Guayabal-san pablo",
      "Guayaquil",
      "Héctor Abad Gómez",
      "Industriales",
      "Jardin botanico",
      "Jesús Nazareno",
      "Juan Pablo II",
      "Juan XIII – La Quiebra",
      "Juan pablo segundo",
      "Kennedy",
      "La 70",
      "La Aguacatala",
      "La América",
      "La Avanzada",
      "La Candelaria",
      "La Castellana",
      "La Colina",
      "La Cruz",
      "La Esperanza",
      "La Esperanza Nº 2",
      "La Floresta",
      "La Florida",
      "La Francia",
      "La Frontera",
      "La Gloria",
      "La Hondonada",
      "La Isla",
      "La Ladera",
      "La Libertad",
      "La Loma de Los Bernal",
      "La Mansión",
      "La Milagrosa",
      "La Mota",
      "La Palma",
      "La Pilarica",
      "La Piñuela",
      "La Pradera",
      "La Rosa",
      "La Salle",
      "La Sierra",
      "La Sierra",
      "La Sierra (Santa Lucía – Las Estancias)",
      "La aurora",
      "La iguaná",
      "Lalinde",
      "Las Acacias",
      "Las Brisas",
      "Las Esmeraldas",
      "Las Estancias",
      "Las Granjas",
      "Las Independencias",
      "Las Lomas Nº 1",
      "Las Lomas Nº 2",
      "Las Mercedes",
      "Las Palmas",
      "Las Playas",
      "Las Violetas",
      "Las vegas",
      "Laureles",
      "Laureles almeria",
      "Llanaditas",
      "Llanaditas",
      "Llanaditas",
      "Loma de los balsos",
      "Loma de los bernal",
      "Loma de san julian",
      "Loma del indio",
      "Lopez de mesa",
      "Lorena",
      "Loreto",
      "Los Alcázares",
      "Los Alpes",
      "Los Balsos Nº 1",
      "Los Balsos Nº 2",
      "Los Cerros El Vergel",
      "Los Colores",
      "Los Conquistadores",
      "Los Mangos",
      "Los Naranjos",
      "Los Pinos",
      "Los balsos",
      "Los Ángeles",
      "López de Mesa",
      "Manila",
      "Manila poblado",
      "Manrique",
      "Manrique Central No. 2",
      "Manrique Central Nº 1",
      "Manrique Oriental",
      "Manrique central",
      "Manrique guadalupe",
      "Manrique jardin",
      "Manrique san blas",
      "Maria Cano – Carambolas",
      "Metropolitano",
      "Mirador del Doce",
      "Miraflores",
      "Miranda",
      "Miravalle",
      "Monteclaro",
      "Moravia",
      "Moscú Nº 1",
      "Moscú Nº 2",
      "NO CONCRETADO",
      "Naranjal",
      "No registra barrio",
      "Noel",
      "Nueva Villa de Aburrá",
      "Nueva Villa de La Iguaná",
      "Nuevos Conquistadores",
      "Nutibara",
      "Ocho de Marzo",
      "Olaya Herrera",
      "Oriente",
      "Pablo VI",
      "Pablo sexto",
      "Pajarito",
      "Palenque",
      "Palermo",
      "Palmas",
      "Palmas retorno #6",
      "Parque Juan Pablo II",
      "Parque berrio",
      "Parque de belen",
      "Parque de las luces",
      "Patio Bonito",
      "Pedregal",
      "Perpetuo Socorro",
      "Perpetuo Socorro",
      "Perpetuo Socorro",
      "Picachito",
      "Picacho",
      "Placita de flores",
      "Poblado",
      "Poblado Oviedo",
      "Poblado loma de alejandria",
      "Poblado oviedo",
      "Poblado provenza",
      "Poblado san lucas",
      "Poblado-castropol",
      "Popular",
      "Popular 2",
      "Pradito",
      "Prado",
      "Prado-centro",
      "Progreso Nº 2",
      "Robledo",
      "Robledo Altamira",
      "Robledo Palenque",
      "Robledo aures",
      "Robledo bello horizonte",
      "Robledo comuna 7",
      "Robledo diamante",
      "Robledo kennedy",
      "Robledo la aurora",
      "Robledo la campiña",
      "Robledo la pola",
      "Robledo las brisas",
      "Robledo miramar",
      "Robledo pajarito",
      "Robledo pelenque",
      "Robledo pilarica",
      "Robledo puerta del sol",
      "Robledo san german",
      "Robledo villa campiña",
      "Robledo villa flora",
      "Robledo villa sofia",
      "Robledo-El diamante",
      "Rodeo alto",
      "Rosales",
      "SAN JUAQUIN",
      "Salvador",
      "San Antonio",
      "San Benito",
      "San Benito",
      "San Benito",
      "San Bernardo",
      "San Diego",
      "San Germán",
      "San Isidro",
      "San Javier Nº 1",
      "San Javier Nº 2",
      "San Joaquín",
      "San José La Cima Nº 1",
      "San José La Cima Nº 2",
      "San Lucas",
      "San Martín de Porres",
      "San Miguel",
      "San Pablo",
      "San Pedro",
      "San antonio de prado",
      "San cristobal",
      "San cristobal-playa rica",
      "San javier",
      "San jeronimo",
      "San jose de la cima",
      "Santa Cruz",
      "Santa Fé",
      "Santa Inés",
      "Santa Lucia",
      "Santa Margarita",
      "Santa María de Los Ángeles",
      "Santa Mónica",
      "Santa Rosa de Lima",
      "Santa Teresita",
      "Santa cruz-parte baja",
      "Santa elena-Corregimiento",
      "Santander",
      "Santo Domingo Sabio Nº 2",
      "Santo Domingo Savio Nº 1",
      "Santo domingo",
      "Sevilla",
      "Simesa",
      "Simon bolivar-Laureles",
      "Simón Bolívar",
      "Sol de oriente",
      "Sucre",
      "Suramericana",
      "Tejelo",
      "Tenche",
      "Terminal del norte",
      "Tinta linda - buenos aires",
      "Toscana",
      "Trece de Noviembre",
      "Tricentenario",
      "Trinidad",
      "Unicentro",
      "Veinte de Julio",
      "Velodromo",
      "Ventura",
      "VeraCruz",
      "VeraCruz",
      "Versalles Nº 1",
      "Versalles Nº 2",
      "Via el jardin",
      "Villa Carlota",
      "Villa Flora",
      "Villa Guadalupe",
      "Villa Hermosa",
      "Villa Lilliam",
      "Villa Niza",
      "Villa Nueva",
      "Villa Turbay",
      "Villa del Socorro",
      "Villa laura",
      "Villa tina",
      "Villatina",
    ],
  },
  {
    nombre: "NARIÑO",
    barrios: [
      "Aguacatal",
      "Alejandría",
      "Cabilditos",
      "Campo Alegre",
      "Damas",
      "El Bosque",
      "El Caraño",
      "El Carmelo",
      "El Cóndor",
      "El Guamito",
      "El Jazmín",
      "El Limón",
      "El Llano",
      "El Palmar",
      "El Piñal",
      "El Recreo",
      "El Sándal",
      "El Verdal",
      "El Zafiro",
      "Guadualito",
      "Guayaquil",
      "La Argentina",
      "La Española",
      "La Hermosa",
      "La Loma",
      "La Palma",
      "La Quiebra",
      "La Soledad",
      "La Unión",
      "Las Brisas",
      "Las Mercedes",
      "Los Medios",
      "Montecristo",
      "Morro Azul",
      "Nechí",
      "Puerto Venus",
      "Quiebra de San Juan",
      "San Andrés",
      "San Antonio",
      "San Isidro",
      "San José",
      "San Rafael",
      "Santa Bárbara",
      "Santa Rosa",
      "Uvital",
      "Villa Fátima",
    ],
  },
  {
    nombre: "RIONEGRO/LLANO GRANDE",
    barrios: [
      "Aeropuerto",
      "Alto Bonito",
      "Altos del Medio",
      "Barro Blanco",
      "Belchite",
      "Betania",
      "Boquerón",
      "Cabeceras",
      "Camargo",
      "Campo Alegre",
      "Centro",
      "Chachafruto",
      "Chipre",
      "Cuatro Esquinas",
      "El Carmín",
      "El Carretero",
      "El Cerro",
      "El Faro",
      "El Rosal ",
      "El Tablazo",
      "El llanto porvenir",
      "El santuario",
      "Fontibón",
      "Galicia",
      "Gualanday",
      "Hospital",
      "La Aurora",
      "La Chapa",
      "La Honda",
      "La Laja ",
      "La Madera",
      "La María",
      "La Mosquita",
      "La Playa",
      "La Primavera",
      "La convencion",
      "Llanogrande",
      "No registra barrio-vereda",
      "Porvenir",
      "Quirama",
      "Sajonia",
      "San Antonio",
      "San Antonio",
      "San Joaquín",
      "San José",
      "San Luis",
      "San Rafael",
      "Santa Ana",
      "Santa Bárbara",
      "Tablacito",
      "Vereda-Vilachagua",
      "Viboral",
      "Vilachuaga",
    ],
  },
  {
    nombre: "SABANETA",
    barrios: [
      "Alcazares",
      "Aliadas Del Sur",
      "Ancon Sur",
      "Aves marias",
      "Betania",
      "CC mayorca",
      "Calle Del Banco",
      "Calle Larga",
      "Cañaveralejo",
      "Ceramica",
      "El Carmelo Ii",
      "El trapiche",
      "Entreamigos",
      "Estacion-sabaneta",
      "Holanda",
      "La Barquereña",
      "La Doctora",
      "La Florida",
      "La inmaculada",
      "Las Casitas",
      "Las Lomitas",
      "Las vegas",
      "Loma de san jose",
      "Loma san jose",
      "Los Alcázarez",
      "Los Arias",
      "Manuel Restrepo",
      "María Auxiliadora",
      "NO CONCRETADO",
      "Natura",
      "No registra barrio",
      "Nuestra Señora de los Dolores",
      "Pan de Azúcar",
      "Parque de sabaneta",
      "Paso Ancho",
      "Playas de María",
      "Prados de Sabaneta",
      "Promisión",
      "Restrepo Naranjo",
      "SAN ISIDRO",
      "Sabaneta Real",
      "San Joaquín",
      "San José",
      "San Rafael",
      "San francisco",
      "Santa Ana",
      "Torre gorrion",
      "Tres Esquinas",
      "Vegas de San José",
      "Vegas de la Doctora",
      "Vegas plaza",
      "Villas del Carmen",
      "Virgen del Carmen",
      "Yarumito",
    ],
  },
  {
    nombre: "SAN FRANCISCO",
    barrios: [
      "Asiento Grande",
      "Boquerón",
      "Buenos Aires",
      "Caunzales",
      "Cañada Honda",
      "Chumurro",
      "Comejenes",
      "El Arrebol",
      "El Brillante",
      "El Castillo",
      "El Jardín",
      "El Jardín de Aquitania",
      "El Pajuí",
      "El Porvenir de Aquitania",
      "El Tagual",
      "El Venado",
      "Farallones",
      "Guacales",
      "La Cristalina",
      "La Eresma",
      "La Esperanza",
      "La Floresta",
      "La Florida",
      "La Fé",
      "La Holanda",
      "La Honda",
      "La Loma",
      "La Lora",
      "La Maravilla",
      "La Nutria",
      "La Veta",
      "Las Aguadas",
      "Pailania",
      "Pocitos",
      "Rancho Largo",
      "San Agustín",
      "San Isidro",
      "San Rafael",
      "Santa Isabel",
      "Venecia",
      "Yerbales",
    ],
  },
  {
    nombre: "SAN JERONIMO",
    barrios: [
      "Alto Colorado",
      "Buenos Aires",
      "Cenegueta",
      "El Calvario",
      "El Chocho",
      "El Pomar",
      "Las Estancias",
      "Los Alticos",
      "Mestizal",
      "No registra barrio-vereda",
      "Quimbayo",
    ],
  },
  {
    nombre: "SAN ROQUE",
    barrios: [
      "Barcino",
      "Cabildo",
      "Candelaria",
      "Chorro Claro",
      "Corocito",
      "Cristales",
      "Efe Gómez",
      "El Brasil",
      "El Carmen",
      "El Diamante",
      "El Diluvio",
      "El Iris",
      "El Porvenir",
      "El Píramo",
      "El Táchira",
      "El Vesubio",
      "Encarnaciones",
      "Frailes",
      "Guacas Abajo",
      "Guacas Arriba",
      "Jardín",
      "La Bella",
      "La Ceiba",
      "La Chinca",
      "La Floresta",
      "La Florida",
      "La Guzmana",
      "La Gómez",
      "La Inmaculada",
      "La Jota",
      "La Linda",
      "La María",
      "La Mora",
      "La Pureza",
      "La Trinidad",
      "Manizales",
      "Marbella",
      "Montemar",
      "Mulatal",
      "Nusito",
      "Palmas",
      "Patio Bonito",
      "Peñas Azules",
      "Playa Rica",
      "Providencia",
      "Quiebrahonda",
      "San Antonio",
      "San Javier",
      "San Joaquín",
      "San José Del Nus",
      "San José del Nare",
      "San Juan",
      "San Matías",
      "San Pablo",
      "Santa Bárbara",
      "Santa Isabel",
      "Santa Teresa (A)",
      "Santa Teresa (B)",
      "no registra",
    ],
  },
  {
    nombre: "SANTA HELENA DE OPON",
    barrios: [
      "Cornétales",
      "Cueva de Pavas Alta",
      "Cueva de Pavas Baja",
      "Culebrosa",
      "El Saltico",
      "El Santuario",
      "Fortuna",
      "No registra barrio-vereda",
      "Pozo Azul",
      "Párameles",
      "San Antonio de la Palma",
      "San Cayetano",
      "San Luis",
      "Sardinas Alta",
      "Sardinas Baja",
      "Vereda-maso",
    ],
  },
  {
    nombre: "SANTAFE DE ANTIOQUIA",
    barrios: [
      "Calle la amargura",
      "Cativo",
      "El Pescado",
      "Guasabra",
      "Los Azules",
      "No registra barrio-vereda",
      "No registro",
      "Sabanas",
      "Tonusco Arriba",
    ],
  },
  {
    nombre: "SANTO DOMINGO",
    barrios: [
      " Botero",
      "Barrio centro",
      "Centro Poblado Botero",
      "Centro Poblado Porcesito",
      "Cubiletes",
      "Danubio",
      "El Cantil",
      "El Carmen",
      "El Chilca",
      "El Limón",
      "El Porvenir",
      "El Rayo",
      "El Rosario",
      "El Saladero",
      "El Tambo",
      "El Uvito",
      "El Ánime",
      "Faldas del Nus",
      "Guadulejo",
      "La Chorrera",
      "La Esperanza",
      "La Floresta",
      "La Honda",
      "La Inmaculada",
      "La M",
      "La Primavera",
      "La Quiebra",
      "La Soledad",
      "La Trinidad",
      "La Trinidad",
      "La Unión",
      "La Vega",
      "Las Beatrices",
      "Las Flores",
      "Las Nutrias",
      "Los Medios",
      "Los Planes",
      "Matasano",
      "Montañita",
      "Montebello",
      "Moroca",
      "No registra barrio-vereda",
      "Pantanillo",
      "Peñas",
      "Piedra Gorda",
      "Playas",
      "Porcesito (Porce)",
      "Raudal",
      "Reyes",
      "San Agustín",
      "San Antonio",
      "San Bartolo",
      "San José",
      "San José",
      "San Lorenzo",
      "San Pedro",
      "San Rafael",
      "Santa Ana",
      "Santa Gertrudis",
      "Santa Rita",
      "Santiago",
      "Vainillal",
      "Versalles",
    ],
  },
  {
    nombre: "SEGOVIA",
    barrios: ["Centro de segovia"],
  },
  {
    nombre: "SONSON",
    barrios: [
      " Aldea",
      " Chagualito",
      " El Trigal",
      " San José",
      "Alto de Sabanas",
      "Buenos Aires",
      "Colombia",
      "El Capiro",
      "El Carmelo",
      "Guanteros",
      "Jerusalén",
      "Kennedy",
      "La Cabaña",
      "La Calzada",
      "La Danta",
      "La Linda",
      "Los Libertadores",
      "Los Llanitos",
      "Los Medios",
      "Los Potreros",
      "Palermo",
      "Río Verde de los Henaos",
      "Río Verde de los Montes",
      "Salomé",
      "San Miguel",
      "Santo Tomás",
      "Tapete",
    ],
  },
  {
    nombre: "SOPETRAN",
    barrios: [
      "El Pomar",
      "El Sauce",
      "Filo Grande",
      "La Isleta",
      "No registra barrio-vereda",
      "Santa Bárbara",
    ],
  },
  {
    nombre: "San Rafael",
    barrios: [
      "Agua Bonita",
      "Boquerón",
      "Camelias",
      "Chico",
      "Churimo",
      "Ciprés",
      "Cuervos",
      "Dantas",
      "Danticas",
      "Dorada",
      "El Arenal",
      "El Bizcocho",
      "El Brasil",
      "El Cardal",
      "El Charco",
      "El Diamante",
      "El Guadual",
      "El Gólgota",
      "El Ingenio",
      "El Jague",
      "El Jardín",
      "El Silencio",
      "Falditas",
      "Farallones",
      "Guadualito",
      "Honda",
      "La Clara",
      "La Cumbre",
      "La Estrella",
      "La Florida",
      "La Granja",
      "La Inmaculada",
      "La Iraca",
      "La Luz",
      "La Mesa",
      "La Pradera",
      "La Rápida",
      "Las Divisas",
      "Las Flores",
      "Los Centros",
      "Los Medios",
      "Macanal",
      "Manila",
      "Media Cuesta",
      "Peñoles",
      "Piedras Abajo",
      "Piedras Arriba",
      "Playas",
      "Puente Tierra",
      "Quebradona",
      "Samaria",
      "San Agustín",
      "San Antonio",
      "San José",
      "San Judas",
      "San Julián",
      "San Miguel",
      "San Miguel",
      "San Rafael",
      "Santa Ana",
      "Santa Bárbara",
      "Santa Cruz",
      "Santa Cruz",
      "Santa Isabel",
      "Santa Rita",
      "Santo Domingo",
      "Santo Tomás",
      "Villa del Socorro",
    ],
  },
  {
    nombre: "San vicente - Ferrer",
    barrios: ["Centro de san vicente"],
  },
];
